"""achievements_awarded table

Revision ID: 085387eae84b
Revises: 2c072e7b6738
Create Date: 2026-07-22 07:43:45.528960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '085387eae84b'
down_revision: Union[str, None] = '2c072e7b6738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements_awarded',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.String(length=64), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'achievement_id', name='uq_award_player_ach')
    )
    with op.batch_alter_table('achievements_awarded', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_achievements_awarded_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements_awarded', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_achievements_awarded_player_id'))

    op.drop_table('achievements_awarded')
    # ### end Alembic commands ###
