"""move_stats v2 columns

Revision ID: 0f765d34883a
Revises: 085387eae84b
Create Date: 2026-07-22 08:16:03.926649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f765d34883a'
down_revision: Union[str, None] = '085387eae84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acpl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('first_bad_move', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_eval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_eval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_cpl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_moves', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('open_blunders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mid_cpl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mid_moves', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mid_blunders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_cpl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_moves', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('end_blunders', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('move_stats', schema=None) as batch_op:
        batch_op.drop_column('end_blunders')
        batch_op.drop_column('end_moves')
        batch_op.drop_column('end_cpl')
        batch_op.drop_column('mid_blunders')
        batch_op.drop_column('mid_moves')
        batch_op.drop_column('mid_cpl')
        batch_op.drop_column('open_blunders')
        batch_op.drop_column('open_moves')
        batch_op.drop_column('open_cpl')
        batch_op.drop_column('min_eval')
        batch_op.drop_column('max_eval')
        batch_op.drop_column('first_bad_move')
        batch_op.drop_column('acpl')

    # ### end Alembic commands ###
