"""move_stats table

Revision ID: 2c072e7b6738
Revises: bbc799a88736
Create Date: 2026-07-20 20:03:35.075169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c072e7b6738'
down_revision: Union[str, None] = 'bbc799a88736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('moves', sa.Integer(), nullable=False),
    sa.Column('brilliant', sa.Integer(), nullable=False),
    sa.Column('great', sa.Integer(), nullable=False),
    sa.Column('best', sa.Integer(), nullable=False),
    sa.Column('excellent', sa.Integer(), nullable=False),
    sa.Column('good', sa.Integer(), nullable=False),
    sa.Column('inaccuracy', sa.Integer(), nullable=False),
    sa.Column('mistake', sa.Integer(), nullable=False),
    sa.Column('blunder', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move_stats')
    # ### end Alembic commands ###
