"""baseline: players, games, rating_snapshots, sync_log

Revision ID: 5c6babe9b843
Revises: 
Create Date: 2026-07-20 14:24:40.694726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5c6babe9b843'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=True)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('time_class', sa.String(length=16), nullable=False),
    sa.Column('time_control', sa.String(length=32), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(length=5), nullable=False),
    sa.Column('opponent', sa.String(length=64), nullable=True),
    sa.Column('opponent_rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('termination', sa.String(length=32), nullable=True),
    sa.Column('my_rating', sa.Integer(), nullable=True),
    sa.Column('eco', sa.String(length=8), nullable=True),
    sa.Column('opening_name', sa.String(length=128), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=True),
    sa.Column('accuracy_mine', sa.Float(), nullable=True),
    sa.Column('accuracy_opponent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_eco'), ['eco'], unique=False)
        batch_op.create_index('ix_games_player_end_time', ['player_id', 'end_time'], unique=False)
        batch_op.create_index('ix_games_player_time_class', ['player_id', 'time_class'], unique=False)

    op.create_table('rating_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('best_rating', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshots_player_mode_taken', ['player_id', 'mode', 'taken_at'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('complete', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'year', 'month', name='uq_sync_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_log')
    with op.batch_alter_table('rating_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_player_mode_taken')

    op.drop_table('rating_snapshots')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index('ix_games_player_time_class')
        batch_op.drop_index('ix_games_player_end_time')
        batch_op.drop_index(batch_op.f('ix_games_eco'))

    op.drop_table('games')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_username'))

    op.drop_table('players')
    # ### end Alembic commands ###
